name: Publish Typedoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publish Typedoc
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4.1.0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - run: pnpm install

      - run: pnpm build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
          cname: nextjs-playground.docs.kitsuyui.com
